const CLASSIFICATION_WEIGHT = {
    'SEM VULNERABILIDADES DETECTADAS': 0,
    'BAIXO RISCO': 25,
    'MÉDIO RISCO': 50,
    'ALTO RISCO': 75,
    'CRÍTICO': 100
};

module.exports = CLASSIFICATION_WEIGHT;